theme = "duckquill"
title = "Home"
base_url = "https://shaostassen.github.io/ShaoFastRobots"


compile_sass = true
minify_html = true
generate_feeds = true

feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "Shao Stassen"

default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
# highlight_code = true
# math = true
# render_html = true
# highlight_theme = "css"
# highlight_themes_css = [
#	{ theme = "solarized-dark", filename = "syntax-theme-dark.css" },
# 	{ theme = "solarized-light", filename = "syntax-theme-light.css" }
# ]
# smart_punctuation = true
# bottom_footnotes = true

[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"

[extra]

# default_theme = "dark"
katex = true
math = true

favicon = "/favicon.png"
accent_color = "#0095ff"
accent_color_dark = "#48d4ff"
fix_contrast_dark = true
bundled_fonts = true


show_copy_button = true
# Whether to show estimated read time in posts.
show_reading_time = true

# Whether to show a share button in article's quick actions.
show_share_button = true

# Whether to show the backlinks button for linked articles in the article's quick actions
show_backlinks = true


# Custom separator used across the theme.
# separator = "•"
# Custom separator used in title tag and posts metadata.
# title_separator = "-"


[extra.nav]
# Whether to show the manual theme switcher in the nav
show_theme_switcher = true


links = [
	{ name = "Projects", menu = [
		{ url = "@/Fast Robots Stuff/_index.md", name = "ECE 4160 Fast Robots" },
	] },
]


[extra.footer]
# Social links in the footer.
# Whether to show "© Title, YEAR"
show_copyright = false
# Whether to show "Powered by Zola and Duckquill"
show_powered_by = false
# Whether to show link to website source
show_source = false
# Custom copyright text
#
# copyright = "© *Aperture* **Science** ~~Innovators~~, `1972`"

[extra.debug]
# Display outlines around all elements for debugging purposes
layout = false
# Don't load any styles for debugging purposes
no_styles = false
